### ISSUE TITLE
Design 

### ISSUE THREAD

**Issue by ShrinidhiVS** [Q-Division-2018-2019/Team-9#1]
Send me the black box image

**Comment by SakshiT1406** [comment]
![screenshot 6](https://user-images.githubusercontent.com/46927928/52530514-e7aa0100-2d2c-11e9-9847-ff3b320f9075.png)

**Comment by SakshiT1406** [comment]
link of the image
![ftreeexp](https://user-images.githubusercontent.com/46927928/52570394-54122680-2e39-11e9-9646-899f627d2657.png)
